services:
  - type: web
    name: dev-challenge-platform
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MYSQLHOST
        sync: false
      - key: MYSQLPORT
        value: "3306"
      - key: MYSQLDATABASE
        sync: false
      - key: MYSQLUSER
        sync: false
      - key: MYSQLPASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
        value: devchallenge_super_secret_key_2024_vaibhav_secure
      - key: JWT_EXPIRATION
        value: "86400000"
    