spring.application.name=devchallenge

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/devchallenge
spring.datasource.username=root
spring.datasource.password=Vaibhav47@#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
jwt.secret=devchallenge_super_secret_key_2024_vaibhav_secure
jwt.expiration=86400000
spring.profiles.active=prod

# Port
server.port=8086